name: achinterbank-onprem

services:
  achinterbank-api:
    build:
      context: .
      dockerfile: src/Cfa.ACHInterbank.Api/Dockerfile
    image: achinterbank-api:local
    container_name: achinterbank-api
    environment:
      Database__Provider: ${DATABASE_PROVIDER:-Postgres}
      ConnectionStrings__PostgresConnection: ${CONNECTIONSTRINGS__POSTGRESCONNECTION:-Host=postgres;Port=5432;Database=${POSTGRES_DB:-ACHInterbank};Username=${POSTGRES_USER:-example_user};Password=${POSTGRES_PASSWORD:-example_password_change_me}}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:8080}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      EnableHttpsRedirection: ${ENABLE_HTTPS_REDIRECTION:-false}
      Database__ApplyMigrations: ${DATABASE_APPLY_MIGRATIONS:-false}
      DigitalEnvelope__CertificateSecretResolver__FailIfSecretProviderUnavailable: "false"
    ports:
      - "843:8080"
    restart: unless-stopped
    networks: [ach_onprem]

  achinterbank-spa:
    build:
      context: ./web/ach-interbank-ui
      dockerfile: Dockerfile
    image: achinterbank-spa:local
    container_name: achinterbank-spa
    ports:
      - "743:80"
    depends_on:
      achinterbank-api:
        condition: service_started
    restart: unless-stopped
    networks: [ach_onprem]

networks:
  ach_onprem:
    driver: bridge

volumes:
  ach_postgres_data:
  ach_sqlserver_data:
