-- NACHA-M enterprise configuration model (PostgreSQL)
-- Phase: persistence baseline + initial backfill from legacy NACHA tables

BEGIN;

CREATE TABLE IF NOT EXISTS "CatClearingHouse" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(20) NOT NULL UNIQUE,
    "Name" varchar(120) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CatDirection" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(20) NOT NULL UNIQUE,
    "NameEs" varchar(80) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CatFlowType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(40) NOT NULL UNIQUE,
    "NameEs" varchar(100) NOT NULL,
    "DirectionDefaultId" integer NULL REFERENCES "CatDirection"("Id") ON DELETE RESTRICT,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CatServiceClass" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(20) NOT NULL,
    "NameEs" varchar(120) NOT NULL,
    "ClearingHouseId" integer NULL REFERENCES "CatClearingHouse"("Id") ON DELETE RESTRICT,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("Code","ClearingHouseId")
);

CREATE TABLE IF NOT EXISTS "CatRecordCode" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(5) NOT NULL UNIQUE,
    "NameEs" varchar(120) NOT NULL,
    "IsMandatoryBase" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CatConfigStatus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(20) NOT NULL UNIQUE,
    "IsEditable" boolean NOT NULL,
    "IsPublishable" boolean NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CatDataSourceType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(40) NOT NULL UNIQUE,
    "NameEs" varchar(120) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CatRuleType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" varchar(40) NOT NULL UNIQUE,
    "NameEs" varchar(120) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CfgProfile" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileCode" varchar(80) NOT NULL UNIQUE,
    "NameEs" varchar(160) NOT NULL,
    "Description" varchar(1000) NULL,
    "ClearingHouseId" integer NOT NULL REFERENCES "CatClearingHouse"("Id") ON DELETE RESTRICT,
    "FlowTypeId" integer NOT NULL REFERENCES "CatFlowType"("Id") ON DELETE RESTRICT,
    "DirectionId" integer NOT NULL REFERENCES "CatDirection"("Id") ON DELETE RESTRICT,
    "ServiceClassId" integer NULL REFERENCES "CatServiceClass"("Id") ON DELETE RESTRICT,
    "ContextPriority" integer NOT NULL DEFAULT 100,
    "EffectiveFrom" timestamp NOT NULL,
    "EffectiveTo" timestamp NULL,
    "StatusId" integer NOT NULL REFERENCES "CatConfigStatus"("Id") ON DELETE RESTRICT,
    "VersionMajor" integer NOT NULL DEFAULT 1,
    "VersionMinor" integer NOT NULL DEFAULT 0,
    "PublishedAt" timestamp NULL,
    "PublishedBy" varchar(120) NULL,
    "SupersedesProfileId" integer NULL REFERENCES "CfgProfile"("Id") ON DELETE RESTRICT,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("ClearingHouseId","FlowTypeId","DirectionId","ServiceClassId","VersionMajor","VersionMinor")
);

CREATE TABLE IF NOT EXISTS "CfgProfileTag" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileId" integer NOT NULL REFERENCES "CfgProfile"("Id") ON DELETE CASCADE,
    "TagKey" varchar(60) NOT NULL,
    "TagValue" varchar(200) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("ProfileId","TagKey","TagValue")
);

CREATE TABLE IF NOT EXISTS "CfgRuleSet" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RuleSetCode" varchar(100) NOT NULL UNIQUE,
    "NameEs" varchar(150) NOT NULL,
    "Description" varchar(1000) NULL,
    "Scope" varchar(30) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CfgLayoutVariant" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileId" integer NOT NULL REFERENCES "CfgProfile"("Id") ON DELETE CASCADE,
    "RecordCodeId" integer NOT NULL REFERENCES "CatRecordCode"("Id") ON DELETE RESTRICT,
    "VariantCode" varchar(120) NOT NULL,
    "NameEs" varchar(180) NOT NULL,
    "Description" varchar(1000) NULL,
    "Priority" integer NOT NULL DEFAULT 100,
    "EffectiveFrom" timestamp NOT NULL,
    "EffectiveTo" timestamp NULL,
    "StatusId" integer NOT NULL REFERENCES "CatConfigStatus"("Id") ON DELETE RESTRICT,
    "TotalLength" integer NOT NULL DEFAULT 106,
    "SelectionPredicateJson" text NULL,
    "IsDefaultForRecord" boolean NOT NULL DEFAULT false,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("ProfileId","RecordCodeId","VariantCode")
);

CREATE TABLE IF NOT EXISTS "CfgFieldSourceDefinition" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DataSourceTypeId" integer NOT NULL REFERENCES "CatDataSourceType"("Id") ON DELETE RESTRICT,
    "ConstantValue" varchar(400) NULL,
    "EntityName" varchar(120) NULL,
    "PropertyPath" varchar(250) NULL,
    "SqlObjectName" varchar(250) NULL,
    "ExpressionDsl" varchar(4000) NULL,
    "ExternalCatalogCode" varchar(120) NULL,
    "FallbackPolicyJson" varchar(2000) NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "CfgLayoutField" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LayoutVariantId" integer NOT NULL REFERENCES "CfgLayoutVariant"("Id") ON DELETE CASCADE,
    "FieldCode" varchar(80) NOT NULL,
    "FieldNameEs" varchar(150) NOT NULL,
    "StartPosition" integer NOT NULL,
    "Length" integer NOT NULL,
    "PadChar" char(1) NOT NULL DEFAULT ' ',
    "Justification" char(1) NOT NULL DEFAULT 'L',
    "FormatMask" varchar(80) NULL,
    "SortOrder" integer NOT NULL,
    "IsVisibleInBackoffice" boolean NOT NULL DEFAULT true,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "SourceDefinitionId" integer NOT NULL REFERENCES "CfgFieldSourceDefinition"("Id") ON DELETE RESTRICT,
    "TransformationPipelineJson" varchar(4000) NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("LayoutVariantId","FieldCode"),
    UNIQUE("LayoutVariantId","StartPosition")
);

CREATE TABLE IF NOT EXISTS "CfgFieldRule" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "LayoutFieldId" integer NOT NULL REFERENCES "CfgLayoutField"("Id") ON DELETE CASCADE,
    "RuleTypeId" integer NOT NULL REFERENCES "CatRuleType"("Id") ON DELETE RESTRICT,
    "RuleCode" varchar(100) NOT NULL,
    "ErrorCode" varchar(60) NOT NULL,
    "ErrorMessageEs" varchar(500) NOT NULL,
    "Severity" varchar(10) NOT NULL,
    "ConditionDsl" varchar(4000) NULL,
    "RuleConfigJson" varchar(4000) NULL,
    "Order" integer NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("LayoutFieldId","RuleCode")
);

CREATE TABLE IF NOT EXISTS "CfgRuleSetRule" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RuleSetId" integer NOT NULL REFERENCES "CfgRuleSet"("Id") ON DELETE CASCADE,
    "RuleTypeId" integer NOT NULL REFERENCES "CatRuleType"("Id") ON DELETE RESTRICT,
    "RuleCode" varchar(100) NOT NULL,
    "ConditionDsl" varchar(4000) NULL,
    "RuleConfigJson" varchar(4000) NULL,
    "ErrorCode" varchar(60) NOT NULL,
    "ErrorMessageEs" varchar(500) NOT NULL,
    "Order" integer NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("RuleSetId","RuleCode")
);

CREATE TABLE IF NOT EXISTS "CfgProfileRecord" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileId" integer NOT NULL REFERENCES "CfgProfile"("Id") ON DELETE CASCADE,
    "RecordCodeId" integer NOT NULL REFERENCES "CatRecordCode"("Id") ON DELETE RESTRICT,
    "Sequence" integer NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "MinOccurs" integer NOT NULL DEFAULT 1,
    "MaxOccurs" integer NULL,
    "SourceStrategy" varchar(40) NOT NULL,
    "LayoutVariantId" integer NULL REFERENCES "CfgLayoutVariant"("Id") ON DELETE RESTRICT,
    "SemanticRuleSetId" integer NULL REFERENCES "CfgRuleSet"("Id") ON DELETE RESTRICT,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    UNIQUE("ProfileId","RecordCodeId","Sequence")
);

CREATE TABLE IF NOT EXISTS "CfgPublishRequest" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileId" integer NOT NULL REFERENCES "CfgProfile"("Id") ON DELETE CASCADE,
    "RequestedBy" varchar(120) NOT NULL,
    "RequestedAt" timestamp NOT NULL,
    "ApprovedBy" varchar(120) NULL,
    "ApprovedAt" timestamp NULL,
    "Status" varchar(20) NOT NULL,
    "ValidationReportJson" varchar(8000) NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "HistConfigSnapshot" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileId" integer NOT NULL REFERENCES "CfgProfile"("Id") ON DELETE RESTRICT,
    "VersionMajor" integer NOT NULL,
    "VersionMinor" integer NOT NULL,
    "SnapshotType" varchar(30) NOT NULL,
    "SnapshotJson" varchar(16000) NOT NULL,
    "CreatedAtUtc" timestamp NOT NULL,
    "CreatedBy" varchar(120) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS "HistConfigChange" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProfileId" integer NOT NULL REFERENCES "CfgProfile"("Id") ON DELETE RESTRICT,
    "EntityName" varchar(120) NOT NULL,
    "EntityId" varchar(120) NOT NULL,
    "ChangeType" varchar(40) NOT NULL,
    "BeforeJson" varchar(16000) NULL,
    "AfterJson" varchar(16000) NULL,
    "ChangedAtUtc" timestamp NOT NULL,
    "ChangedBy" varchar(120) NOT NULL,
    "CorrelationId" varchar(120) NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" timestamptz NOT NULL DEFAULT timezone('utc', now())
);

INSERT INTO "CatClearingHouse"("Code","Name","IsActive")
SELECT 'ACH','ACH Colombia',true WHERE NOT EXISTS(SELECT 1 FROM "CatClearingHouse" WHERE "Code"='ACH');
INSERT INTO "CatClearingHouse"("Code","Name","IsActive")
SELECT 'CENIT','CENIT',true WHERE NOT EXISTS(SELECT 1 FROM "CatClearingHouse" WHERE "Code"='CENIT');

INSERT INTO "CatConfigStatus"("Code","IsEditable","IsPublishable")
SELECT 'BORRADOR',true,true WHERE NOT EXISTS(SELECT 1 FROM "CatConfigStatus" WHERE "Code"='BORRADOR');
INSERT INTO "CatConfigStatus"("Code","IsEditable","IsPublishable")
SELECT 'PUBLICADO',false,false WHERE NOT EXISTS(SELECT 1 FROM "CatConfigStatus" WHERE "Code"='PUBLICADO');
INSERT INTO "CatConfigStatus"("Code","IsEditable","IsPublishable")
SELECT 'INACTIVO',false,false WHERE NOT EXISTS(SELECT 1 FROM "CatConfigStatus" WHERE "Code"='INACTIVO');
INSERT INTO "CatConfigStatus"("Code","IsEditable","IsPublishable")
SELECT 'ARCHIVADO',false,false WHERE NOT EXISTS(SELECT 1 FROM "CatConfigStatus" WHERE "Code"='ARCHIVADO');

-- Backfill mínima: se deja a seeder de aplicación para preservar reglas de mapping C#.

COMMIT;
