//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsAutorizadorOM
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfBancaMovil")]
    public partial class CompositeType : object
    {
        
        private string JsonInputField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonInput
        {
            get
            {
                return this.JsonInputField;
            }
            set
            {
                this.JsonInputField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamCNBTercerizados", Namespace="http://schemas.datacontract.org/2004/07/WcfBancaMovil")]
    public partial class ParamCNBTercerizados : object
    {
        
        private string InputCNBTercerizadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputCNBTercerizados
        {
            get
            {
                return this.InputCNBTercerizadosField;
            }
            set
            {
                this.InputCNBTercerizadosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamPSE", Namespace="http://schemas.datacontract.org/2004/07/WcfBancaMovil")]
    public partial class ParamPSE : object
    {
        
        private string InputPSEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputPSE
        {
            get
            {
                return this.InputPSEField;
            }
            set
            {
                this.InputPSEField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamTransfiya", Namespace="http://schemas.datacontract.org/2004/07/WcfBancaMovil")]
    public partial class ParamTransfiya : object
    {
        
        private string InputTransfiyaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputTransfiya
        {
            get
            {
                return this.InputTransfiyaField;
            }
            set
            {
                this.InputTransfiyaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamRedeban", Namespace="http://schemas.datacontract.org/2004/07/WcfBancaMovil")]
    public partial class ParamRedeban : object
    {
        
        private string InputRedebanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InputRedeban
        {
            get
            {
                return this.InputRedebanField;
            }
            set
            {
                this.InputRedebanField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsAutorizadorOM.Iinico")]
    public interface Iinico
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnPrincipalBancaMovil", ReplyAction="http://tempuri.org/Iinico/FnPrincipalBancaMovilResponse")]
        string FnPrincipalBancaMovil(wsAutorizadorOM.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnPrincipalBancaMovil", ReplyAction="http://tempuri.org/Iinico/FnPrincipalBancaMovilResponse")]
        System.Threading.Tasks.Task<string> FnPrincipalBancaMovilAsync(wsAutorizadorOM.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnCNBTercerizados", ReplyAction="http://tempuri.org/Iinico/FnCNBTercerizadosResponse")]
        string FnCNBTercerizados(wsAutorizadorOM.ParamCNBTercerizados ParamCNBTercerizados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnCNBTercerizados", ReplyAction="http://tempuri.org/Iinico/FnCNBTercerizadosResponse")]
        System.Threading.Tasks.Task<string> FnCNBTercerizadosAsync(wsAutorizadorOM.ParamCNBTercerizados ParamCNBTercerizados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnPSE", ReplyAction="http://tempuri.org/Iinico/FnPSEResponse")]
        string FnPSE(wsAutorizadorOM.ParamPSE ParamPSE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnPSE", ReplyAction="http://tempuri.org/Iinico/FnPSEResponse")]
        System.Threading.Tasks.Task<string> FnPSEAsync(wsAutorizadorOM.ParamPSE ParamPSE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnTransfiya", ReplyAction="http://tempuri.org/Iinico/FnTransfiyaResponse")]
        string FnTransfiya(wsAutorizadorOM.ParamTransfiya ParamTransfiya);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnTransfiya", ReplyAction="http://tempuri.org/Iinico/FnTransfiyaResponse")]
        System.Threading.Tasks.Task<string> FnTransfiyaAsync(wsAutorizadorOM.ParamTransfiya ParamTransfiya);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnRedeban", ReplyAction="http://tempuri.org/Iinico/FnRedebanResponse")]
        string FnRedeban(wsAutorizadorOM.ParamRedeban ParamRedeban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iinico/FnRedeban", ReplyAction="http://tempuri.org/Iinico/FnRedebanResponse")]
        System.Threading.Tasks.Task<string> FnRedebanAsync(wsAutorizadorOM.ParamRedeban ParamRedeban);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IinicoChannel : wsAutorizadorOM.Iinico, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class IinicoClient : System.ServiceModel.ClientBase<wsAutorizadorOM.Iinico>, wsAutorizadorOM.Iinico
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IinicoClient() : 
                base(IinicoClient.GetDefaultBinding(), IinicoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Iinico.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IinicoClient(EndpointConfiguration endpointConfiguration) : 
                base(IinicoClient.GetBindingForEndpoint(endpointConfiguration), IinicoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IinicoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IinicoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IinicoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IinicoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IinicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string FnPrincipalBancaMovil(wsAutorizadorOM.CompositeType composite)
        {
            return base.Channel.FnPrincipalBancaMovil(composite);
        }
        
        public System.Threading.Tasks.Task<string> FnPrincipalBancaMovilAsync(wsAutorizadorOM.CompositeType composite)
        {
            return base.Channel.FnPrincipalBancaMovilAsync(composite);
        }
        
        public string FnCNBTercerizados(wsAutorizadorOM.ParamCNBTercerizados ParamCNBTercerizados)
        {
            return base.Channel.FnCNBTercerizados(ParamCNBTercerizados);
        }
        
        public System.Threading.Tasks.Task<string> FnCNBTercerizadosAsync(wsAutorizadorOM.ParamCNBTercerizados ParamCNBTercerizados)
        {
            return base.Channel.FnCNBTercerizadosAsync(ParamCNBTercerizados);
        }
        
        public string FnPSE(wsAutorizadorOM.ParamPSE ParamPSE)
        {
            return base.Channel.FnPSE(ParamPSE);
        }
        
        public System.Threading.Tasks.Task<string> FnPSEAsync(wsAutorizadorOM.ParamPSE ParamPSE)
        {
            return base.Channel.FnPSEAsync(ParamPSE);
        }
        
        public string FnTransfiya(wsAutorizadorOM.ParamTransfiya ParamTransfiya)
        {
            return base.Channel.FnTransfiya(ParamTransfiya);
        }
        
        public System.Threading.Tasks.Task<string> FnTransfiyaAsync(wsAutorizadorOM.ParamTransfiya ParamTransfiya)
        {
            return base.Channel.FnTransfiyaAsync(ParamTransfiya);
        }
        
        public string FnRedeban(wsAutorizadorOM.ParamRedeban ParamRedeban)
        {
            return base.Channel.FnRedeban(ParamRedeban);
        }
        
        public System.Threading.Tasks.Task<string> FnRedebanAsync(wsAutorizadorOM.ParamRedeban ParamRedeban)
        {
            return base.Channel.FnRedebanAsync(ParamRedeban);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Iinico))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Iinico))
            {
                return new System.ServiceModel.EndpointAddress("http://tarjconti3:8047/Inicio.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IinicoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Iinico);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IinicoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Iinico);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Iinico,
        }
    }
}
