// <auto-generated />
using System;
using Cfa.ACHInterbank.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cfa.ACHInterbank.Persistence.Migrations
{
    [DbContext(typeof(AchDbContext))]
    [Migration("20251126035842_AddDynamicMenuSchema")]
    partial class AddDynamicMenuSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Menú principal",
                            IsActive = true,
                            Name = "Principal"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Exact")
                        .HasColumnType("bit");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Exact = true,
                            Icon = "dashboard",
                            IsActive = true,
                            Label = "Dashboard",
                            MenuId = 1,
                            Order = 1,
                            Route = "/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            Exact = true,
                            Icon = "group",
                            IsActive = true,
                            Label = "Usuarios",
                            MenuId = 1,
                            Order = 2,
                            Route = "/users"
                        },
                        new
                        {
                            Id = 3,
                            Exact = true,
                            Icon = "key",
                            IsActive = true,
                            Label = "Alias",
                            MenuId = 1,
                            Order = 3,
                            Route = "/aliases"
                        },
                        new
                        {
                            Id = 4,
                            Exact = true,
                            Icon = "schedule",
                            IsActive = true,
                            Label = "Ciclos ACH",
                            MenuId = 1,
                            Order = 4,
                            Route = "/ach-cycles"
                        },
                        new
                        {
                            Id = 5,
                            Exact = true,
                            Icon = "inventory",
                            IsActive = true,
                            Label = "Catálogos",
                            MenuId = 1,
                            Order = 5,
                            Route = "/catalogs"
                        },
                        new
                        {
                            Id = 6,
                            Exact = false,
                            Icon = "swap_horiz",
                            IsActive = true,
                            Label = "Transacciones",
                            MenuId = 1,
                            Order = 6,
                            Route = "/transactions"
                        },
                        new
                        {
                            Id = 7,
                            Exact = true,
                            Icon = "note_add",
                            IsActive = true,
                            Label = "Crear transacción",
                            MenuId = 1,
                            Order = 1,
                            ParentId = 6,
                            Route = "/transactions/create"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItemPermission", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MenuItemId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("MenuItemPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            MenuItemId = 2,
                            PermissionId = new Guid("b5d45f3c-8ac2-4a8b-80d1-315063e27fdf")
                        },
                        new
                        {
                            MenuItemId = 3,
                            PermissionId = new Guid("0ee0a30f-48b6-4b8c-9afd-0dfb3d4770e7")
                        },
                        new
                        {
                            MenuItemId = 4,
                            PermissionId = new Guid("4f0cbde9-1b2e-4ad8-b8e6-62f0a1cd6cf7")
                        },
                        new
                        {
                            MenuItemId = 5,
                            PermissionId = new Guid("dd0e54be-b6df-4ab3-8783-0f72b6e774a2")
                        },
                        new
                        {
                            MenuItemId = 6,
                            PermissionId = new Guid("a6c3bd53-111a-48a3-8d4a-2d1a37c4b86a")
                        },
                        new
                        {
                            MenuItemId = 6,
                            PermissionId = new Guid("4f0cbde9-1b2e-4ad8-b8e6-62f0a1cd6cf7")
                        },
                        new
                        {
                            MenuItemId = 7,
                            PermissionId = new Guid("a6c3bd53-111a-48a3-8d4a-2d1a37c4b86a")
                        },
                        new
                        {
                            MenuItemId = 7,
                            PermissionId = new Guid("4f0cbde9-1b2e-4ad8-b8e6-62f0a1cd6cf7")
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItemRole", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MenuItemId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("MenuItemRoles", (string)null);

                    b.HasData(
                        new
                        {
                            MenuItemId = 2,
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1")
                        },
                        new
                        {
                            MenuItemId = 6,
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1")
                        },
                        new
                        {
                            MenuItemId = 6,
                            RoleId = new Guid("a51746c2-0710-4d79-97b1-5b4368326f56")
                        },
                        new
                        {
                            MenuItemId = 7,
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1")
                        },
                        new
                        {
                            MenuItemId = 7,
                            RoleId = new Guid("a51746c2-0710-4d79-97b1-5b4368326f56")
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarPolicy")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConcurrencyPolicy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<int?>("Minute")
                        .HasColumnType("int");

                    b.Property<int?>("MonthDay")
                        .HasColumnType("int");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeriodicityType")
                        .HasColumnType("int");

                    b.Property<int>("RetryBackoffSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("RetryOnFailure")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("TimeOfDayTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WeeklyDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TaskDefinition", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId");

                    b.ToTable("TaskExecutionLog", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId", "Key")
                        .IsUnique();

                    b.ToTable("TaskParameters", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Expiration")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6c3bd53-111a-48a3-8d4a-2d1a37c4b86a"),
                            Description = "Gestión completa de operaciones ACH",
                            Name = "CanManageAch"
                        },
                        new
                        {
                            Id = new Guid("4f0cbde9-1b2e-4ad8-b8e6-62f0a1cd6cf7"),
                            Description = "Consulta de operaciones ACH",
                            Name = "CanReadAch"
                        },
                        new
                        {
                            Id = new Guid("0ee0a30f-48b6-4b8c-9afd-0dfb3d4770e7"),
                            Description = "Consulta de alias",
                            Name = "CanReadAliases"
                        },
                        new
                        {
                            Id = new Guid("dd0e54be-b6df-4ab3-8783-0f72b6e774a2"),
                            Description = "Consulta de catálogos",
                            Name = "CanReadCatalogs"
                        },
                        new
                        {
                            Id = new Guid("b5d45f3c-8ac2-4a8b-80d1-315063e27fdf"),
                            Description = "Gestión de usuarios",
                            Name = "CanManageUsers"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1"),
                            Description = "Acceso completo al sistema",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a51746c2-0710-4d79-97b1-5b4368326f56"),
                            Description = "Operaciones básicas sobre ACH",
                            Name = "ACH.Operator"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1"),
                            PermissionId = new Guid("a6c3bd53-111a-48a3-8d4a-2d1a37c4b86a")
                        },
                        new
                        {
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1"),
                            PermissionId = new Guid("4f0cbde9-1b2e-4ad8-b8e6-62f0a1cd6cf7")
                        },
                        new
                        {
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1"),
                            PermissionId = new Guid("0ee0a30f-48b6-4b8c-9afd-0dfb3d4770e7")
                        },
                        new
                        {
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1"),
                            PermissionId = new Guid("dd0e54be-b6df-4ab3-8783-0f72b6e774a2")
                        },
                        new
                        {
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1"),
                            PermissionId = new Guid("b5d45f3c-8ac2-4a8b-80d1-315063e27fdf")
                        },
                        new
                        {
                            RoleId = new Guid("a51746c2-0710-4d79-97b1-5b4368326f56"),
                            PermissionId = new Guid("a6c3bd53-111a-48a3-8d4a-2d1a37c4b86a")
                        },
                        new
                        {
                            RoleId = new Guid("a51746c2-0710-4d79-97b1-5b4368326f56"),
                            PermissionId = new Guid("4f0cbde9-1b2e-4ad8-b8e6-62f0a1cd6cf7")
                        },
                        new
                        {
                            RoleId = new Guid("a51746c2-0710-4d79-97b1-5b4368326f56"),
                            PermissionId = new Guid("0ee0a30f-48b6-4b8c-9afd-0dfb3d4770e7")
                        },
                        new
                        {
                            RoleId = new Guid("a51746c2-0710-4d79-97b1-5b4368326f56"),
                            PermissionId = new Guid("dd0e54be-b6df-4ab3-8783-0f72b6e774a2")
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f7d6a26-df0e-4b14-8734-3280c1da6e3d"),
                            Email = "admin@achinterbank.local",
                            FullName = "Administrador ACH",
                            IsActive = true,
                            PasswordHash = "664819d8c5343676c9225b5ed00a5cdc6f3a1ff3",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0f7d6a26-df0e-4b14-8734-3280c1da6e3d"),
                            RoleId = new Guid("1f8602da-6415-43f8-b61d-cb396f8577f1")
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AchCycleId")
                        .HasColumnType("int");

                    b.Property<int>("BatchSequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompanyEntryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyIdentification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("EffectiveEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginOrOdfi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AchCycleId");

                    b.ToTable("AchBatches", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("CutoffTime")
                        .HasColumnType("time");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("date");

                    b.Property<bool>("RescheduleOnHoliday")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId", "ProcessingDate", "CycleName")
                        .IsUnique();

                    b.ToTable("AchCycles");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchBatchId")
                        .HasColumnType("int");

                    b.Property<int>("AchCycleId")
                        .HasColumnType("int");

                    b.Property<bool>("AddendaRecordIndicator")
                        .HasColumnType("bit");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyEntryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyIdentification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationInstitutionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginatingDFI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivingDFI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("TraceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TraceSequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AchBatchId");

                    b.HasIndex("AchCycleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationInstitutionId");

                    b.HasIndex("SourceInstitutionId");

                    b.ToTable("AchTransactions", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransactionAddenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("AddendaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AchTransactionId");

                    b.ToTable("AchTransactionAddenda", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AddendaRecord", b =>
                {
                    b.Property<int>("AddendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddendaID"));

                    b.Property<string>("AddendumSequence")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodeTypeAddendumRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryDetailSequenceNumber")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdUserOrig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfofromOriginator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceOrAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PurposeOfTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddendaID");

                    b.HasIndex("NachaID");

                    b.ToTable("AddendaRecords", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BankHolidayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankHolidays");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchControl", b =>
                {
                    b.Property<int>("BatchControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchControlID"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchTranClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodAutMessage")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("EntryAddendaCount")
                        .HasColumnType("int");

                    b.Property<string>("IdOrigEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUserOrig")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TotalCreditAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDebitAmount")
                        .HasColumnType("money");

                    b.Property<int?>("TotalEntry")
                        .HasColumnType("int");

                    b.HasKey("BatchControlID");

                    b.HasIndex("NachaID");

                    b.ToTable("BatchControls", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchHeader", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchID"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompanyEntryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CompensationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptiveDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscretionaryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectiveEntryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OriginParticipantEntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginUserStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardEntryClassCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("BatchID");

                    b.HasIndex("NachaID");

                    b.ToTable("BatchHeaders", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ClearingHouses");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<string>("HolidayStrategy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId")
                        .IsUnique();

                    b.ToTable("ClearingHouseConfigs");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseCycleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CutoffTime")
                        .HasColumnType("time");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("ClearingHouseCycleConfigs");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Colombia");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("CustomerEmails", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("CustomerPhones", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.EntryDetail", b =>
                {
                    b.Property<int>("EntryDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryDetailID"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("AddendumIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<string>("CheckDigit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscreData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReceivingParticipantEntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipIdNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RecipUserName")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("SequenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryDetailID");

                    b.HasIndex("NachaID");

                    b.ToTable("EntryDetails", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FileControl", b =>
                {
                    b.Property<int>("FileControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileControlID"));

                    b.Property<int>("BatchCount")
                        .HasColumnType("int");

                    b.Property<int>("BlockCount")
                        .HasColumnType("int");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("int");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TotalControl")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalCreditAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDebitAmount")
                        .HasColumnType("money");

                    b.HasKey("FileControlID");

                    b.HasIndex("NachaID");

                    b.ToTable("FileControls", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckDigit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDefaultSource")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TransitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("FinancialInstitutions", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.InstitutionClearingHousePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialInstitutionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.HasIndex("FinancialInstitutionId", "ClearingHouseId")
                        .IsUnique();

                    b.ToTable("InstitutionClearingHousePreferences", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.Property<string>("NachaID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("AchCycleId")
                        .HasColumnType("int");

                    b.Property<string>("BlockingFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int");

                    b.Property<string>("FileCreationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileCreationTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileIdModifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateDestination")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImmediateDestinationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateOrigin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImmediateOriginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NachaID");

                    b.HasIndex("AchCycleId");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("NachaHeaders", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaRecordField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DbColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("NachaRecordLayoutId")
                        .HasColumnType("int");

                    b.Property<string>("PadChar")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("StartPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NachaRecordLayoutId");

                    b.ToTable("NachaRecordFields");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaRecordLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NachaRecordLayouts");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItem", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.Navigation.Menu", "Menu")
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Menu");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItemPermission", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItem", "MenuItem")
                        .WithMany("MenuItemPermissions")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.User.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItemRole", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItem", "MenuItem")
                        .WithMany("MenuItemRoles")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.User.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskExecutionLog", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", "TaskDefinition")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskParameter", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", "TaskDefinition")
                        .WithMany("Parameters")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.PasswordResetToken", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.User.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.RolePermission", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.User.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.User.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.UserRole", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.User.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.User.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchBatch", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", "AchCycle")
                        .WithMany("Batches")
                        .HasForeignKey("AchCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AchCycle");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany("AchCycles")
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchBatch", "AchBatch")
                        .WithMany("Transactions")
                        .HasForeignKey("AchBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", "AchCycle")
                        .WithMany("Transactions")
                        .HasForeignKey("AchCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "DestinationInstitution")
                        .WithMany("DestinationTransactions")
                        .HasForeignKey("DestinationInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "SourceInstitution")
                        .WithMany("SourceTransactions")
                        .HasForeignKey("SourceInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AchBatch");

                    b.Navigation("AchCycle");

                    b.Navigation("DestinationInstitution");

                    b.Navigation("SourceInstitution");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransactionAddenda", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", "Transaction")
                        .WithMany("Addendas")
                        .HasForeignKey("AchTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AddendaRecord", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("AddendaRecords")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchControl", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("BatchControls")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchHeader", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("Batches")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", "ClearingHouseConfig")
                        .WithMany("ClearingHouses")
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClearingHouseConfig");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseCycleConfig", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany()
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerAddress", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerEmail", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", "Customer")
                        .WithMany("Emails")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerPhone", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", "Customer")
                        .WithMany("Phones")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.EntryDetail", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("EntryDetails")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FileControl", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("FileControls")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", null)
                        .WithMany("FinancialInstitutions")
                        .HasForeignKey("ClearingHouseId");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.InstitutionClearingHousePreference", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany()
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "FinancialInstitution")
                        .WithMany("ClearingHousePreferences")
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouse");

                    b.Navigation("FinancialInstitution");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", "AchCycle")
                        .WithMany("NachaHeaders")
                        .HasForeignKey("AchCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany()
                        .HasForeignKey("ClearingHouseId");

                    b.Navigation("AchCycle");

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaRecordField", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaRecordLayout", "Layout")
                        .WithMany("Fields")
                        .HasForeignKey("NachaRecordLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.Menu", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.Navigation.MenuItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuItemPermissions");

                    b.Navigation("MenuItemRoles");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", b =>
                {
                    b.Navigation("ExecutionLogs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.User.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchBatch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("NachaHeaders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.Navigation("Addendas");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.Navigation("AchCycles");

                    b.Navigation("FinancialInstitutions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", b =>
                {
                    b.Navigation("ClearingHouses");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Emails");

                    b.Navigation("Phones");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.Navigation("ClearingHousePreferences");

                    b.Navigation("DestinationTransactions");

                    b.Navigation("SourceTransactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.Navigation("AddendaRecords");

                    b.Navigation("BatchControls");

                    b.Navigation("Batches");

                    b.Navigation("EntryDetails");

                    b.Navigation("FileControls");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaRecordLayout", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
