// <auto-generated />
using System;
using Cfa.ACHInterbank.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cfa.ACHInterbank.Persistence.Migrations
{
    [DbContext(typeof(AchDbContext))]
    [Migration("20250811220009_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CutoffTime")
                        .HasColumnType("time");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RescheduleOnHoliday")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("AchCycles");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchCycleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AchCycleId");

                    b.HasIndex("DestinationInstitutionId");

                    b.HasIndex("SourceInstitutionId");

                    b.ToTable("AchTransactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AddendaRecord", b =>
                {
                    b.Property<int>("AddendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddendaID"));

                    b.Property<string>("AddendumSequence")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodeTypeAddendumRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryDetailSequenceNumber")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdUserOrig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfofromOriginator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceOrAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NachaID")
                        .HasColumnType("int");

                    b.Property<string>("PurposeOfTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddendaID");

                    b.HasIndex("NachaID");

                    b.ToTable("AddendaRecords", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BankHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankHolidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Año Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de los Reyes Magos"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "San José"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jueves Santo"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Viernes Santo"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día del Trabajo"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ascensión del Señor"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corpus Christi"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sagrado Corazón"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de la Independencia"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Batalla de Boyacá"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "La Asunción"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de la Raza"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Todos los Santos"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Independencia de Cartagena"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Inmaculada Concepción"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Navidad"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchControl", b =>
                {
                    b.Property<int>("BatchControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchControlID"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchTranClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodAutMessage")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("EntryAddendaCount")
                        .HasColumnType("int");

                    b.Property<string>("IdOrigEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUserOrig")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NachaID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalEntry")
                        .HasColumnType("int");

                    b.HasKey("BatchControlID");

                    b.HasIndex("NachaID");

                    b.ToTable("BatchControls", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchHeader", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchID"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompanyEntryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CompensationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptiveDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscretionaryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectiveEntryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NachaID")
                        .HasColumnType("int");

                    b.Property<string>("OriginParticipantEntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginUserStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardEntryClassCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("BatchID");

                    b.HasIndex("NachaID");

                    b.ToTable("BatchHeaders", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("ClearingHouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClearingHouseId = 1,
                            Code = "ACHCOL",
                            Name = "ACH Colombia"
                        },
                        new
                        {
                            Id = 2,
                            ClearingHouseId = 1,
                            Code = "CENIT",
                            Name = "CENIT"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<string>("HolidayStrategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClearingHouseConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClearingHouseId = 1,
                            HolidayStrategy = "Colombian"
                        });
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.EntryDetail", b =>
                {
                    b.Property<int>("EntryDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryDetailID"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("AddendumIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckDigit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscreData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NachaID")
                        .HasColumnType("int");

                    b.Property<string>("ReceivingParticipantEntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipIdNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RecipUserName")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("SequenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryDetailID");

                    b.HasIndex("NachaID");

                    b.ToTable("EntryDetails", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FileControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchCount")
                        .HasColumnType("int");

                    b.Property<int>("BlockCount")
                        .HasColumnType("int");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryHash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NachaHeaderId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NachaHeaderId");

                    b.ToTable("FileControls", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FinancialInstitutions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.Property<int>("NachaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NachaID"));

                    b.Property<string>("BlockingFactor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileCreationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileCreationTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileIdModifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateDestination")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImmediateDestinationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateOrigin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImmediateOriginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordSize")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NachaID");

                    b.ToTable("NachaHeaders", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany("AchCycles")
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", "AchCycle")
                        .WithMany("Transactions")
                        .HasForeignKey("AchCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "DestinationInstitution")
                        .WithMany("DestinationTransactions")
                        .HasForeignKey("DestinationInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "SourceInstitution")
                        .WithMany("SourceTransactions")
                        .HasForeignKey("SourceInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AchCycle");

                    b.Navigation("DestinationInstitution");

                    b.Navigation("SourceInstitution");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AddendaRecord", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("AddendaRecords")
                        .HasForeignKey("NachaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchControl", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("BatchControls")
                        .HasForeignKey("NachaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchHeader", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("Batches")
                        .HasForeignKey("NachaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", "ClearingHouseConfig")
                        .WithMany("ClearingHouses")
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouseConfig");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.EntryDetail", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("EntryDetails")
                        .HasForeignKey("NachaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FileControl", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany()
                        .HasForeignKey("NachaHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.Navigation("AchCycles");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", b =>
                {
                    b.Navigation("ClearingHouses");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.Navigation("DestinationTransactions");

                    b.Navigation("SourceTransactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.Navigation("AddendaRecords");

                    b.Navigation("BatchControls");

                    b.Navigation("Batches");

                    b.Navigation("EntryDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
