// <auto-generated />
using System;
using Cfa.ACHInterbank.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cfa.ACHInterbank.Persistence.Migrations
{
    [DbContext(typeof(AchDbContext))]
    partial class AchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarPolicy")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConcurrencyPolicy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<int?>("Minute")
                        .HasColumnType("int");

                    b.Property<int?>("MonthDay")
                        .HasColumnType("int");

                    b.Property<int?>("N")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeriodicityType")
                        .HasColumnType("int");

                    b.Property<int>("RetryBackoffSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("RetryOnFailure")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("TimeOfDayTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("WeeklyDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TaskDefinition", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId");

                    b.ToTable("TaskExecutionLog", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TaskDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("TaskDefinitionId", "Key")
                        .IsUnique();

                    b.ToTable("TaskParameters", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeSpan>("CutoffTime")
                        .HasColumnType("time");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RescheduleOnHoliday")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("AchCycles");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchCycleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceInstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AchCycleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DestinationInstitutionId");

                    b.HasIndex("SourceInstitutionId");

                    b.ToTable("AchTransactions", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransactionAddenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("AddendaType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("AchTransactionId");

                    b.ToTable("AchTransactionAddenda", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AddendaRecord", b =>
                {
                    b.Property<int>("AddendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddendaID"));

                    b.Property<string>("AddendumSequence")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodeTypeAddendumRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryDetailSequenceNumber")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("IdUserOrig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfofromOriginator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceOrAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PurposeOfTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddendaID");

                    b.HasIndex("NachaID");

                    b.ToTable("AddendaRecords", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BankHolidayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankHolidays");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchControl", b =>
                {
                    b.Property<int>("BatchControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchControlID"));

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchTranClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodAutMessage")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("EntryAddendaCount")
                        .HasColumnType("int");

                    b.Property<string>("IdOrigEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdUserOrig")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TotalCreditAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDebitAmount")
                        .HasColumnType("money");

                    b.Property<int?>("TotalEntry")
                        .HasColumnType("int");

                    b.HasKey("BatchControlID");

                    b.HasIndex("NachaID");

                    b.ToTable("BatchControls", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchHeader", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchID"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("CompanyEntryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CompensationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptiveDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscretionaryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectiveEntryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OriginParticipantEntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginUserStatusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceClassCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardEntryClassCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("BatchID");

                    b.HasIndex("NachaID");

                    b.ToTable("BatchHeaders", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("ClearingHouses");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<string>("HolidayStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClearingHouseConfigs");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseCycleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CutoffTime")
                        .HasColumnType("time");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("ClearingHouseCycleConfigs");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Colombia");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAddresses", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("CustomerEmails", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "IsPrimary")
                        .IsUnique()
                        .HasFilter("[IsPrimary] = 1");

                    b.ToTable("CustomerPhones", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.EntryDetail", b =>
                {
                    b.Property<int>("EntryDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryDetailID"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("AddendumIndicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("money");

                    b.Property<string>("CheckDigit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscreData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReceivingParticipantEntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipIdNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RecipUserName")
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.Property<string>("SequenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryDetailID");

                    b.HasIndex("NachaID");

                    b.ToTable("EntryDetails", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FileControl", b =>
                {
                    b.Property<int>("FileControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileControlID"));

                    b.Property<int>("BatchCount")
                        .HasColumnType("int");

                    b.Property<int>("BlockCount")
                        .HasColumnType("int");

                    b.Property<int>("EntryAddendaCount")
                        .HasColumnType("int");

                    b.Property<string>("NachaID")
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("TotalControl")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalCreditAmount")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalDebitAmount")
                        .HasColumnType("money");

                    b.HasKey("FileControlID");

                    b.HasIndex("NachaID");

                    b.ToTable("FileControls", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckDigit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDefaultSource")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TransitCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("FinancialInstitutions", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.InstitutionClearingHousePreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<int>("FinancialInstitutionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("ClearingHouseId");

                    b.HasIndex("FinancialInstitutionId", "ClearingHouseId")
                        .IsUnique();

                    b.ToTable("InstitutionClearingHousePreferences", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.Property<string>("NachaID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("AchCycleId")
                        .HasColumnType("int");

                    b.Property<string>("BlockingFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClearingHouseId")
                        .HasColumnType("int");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int");

                    b.Property<string>("FileCreationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileCreationTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileIdModifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateDestination")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImmediateDestinationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateOrigin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ImmediateOriginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NachaID");

                    b.HasIndex("AchCycleId");

                    b.HasIndex("ClearingHouseId");

                    b.ToTable("NachaHeaders", (string)null);
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskExecutionLog", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", "TaskDefinition")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskParameter", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", "TaskDefinition")
                        .WithMany("Parameters")
                        .HasForeignKey("TaskDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskDefinition");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany("AchCycles")
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", "AchCycle")
                        .WithMany("Transactions")
                        .HasForeignKey("AchCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "DestinationInstitution")
                        .WithMany("DestinationTransactions")
                        .HasForeignKey("DestinationInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "SourceInstitution")
                        .WithMany("SourceTransactions")
                        .HasForeignKey("SourceInstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AchCycle");

                    b.Navigation("DestinationInstitution");

                    b.Navigation("SourceInstitution");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransactionAddenda", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", "Transaction")
                        .WithMany("Addendas")
                        .HasForeignKey("AchTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AddendaRecord", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("AddendaRecords")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchControl", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("BatchControls")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.BatchHeader", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("Batches")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", "ClearingHouseConfig")
                        .WithMany("ClearingHouses")
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouseConfig");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseCycleConfig", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany()
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerAddress", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerEmail", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", "Customer")
                        .WithMany("Emails")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.CustomerPhone", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.Customer", "Customer")
                        .WithMany("Phones")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.EntryDetail", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("EntryDetails")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FileControl", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", "NachaHeader")
                        .WithMany("FileControls")
                        .HasForeignKey("NachaID");

                    b.Navigation("NachaHeader");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany("FinancialInstitutions")
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.InstitutionClearingHousePreference", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany()
                        .HasForeignKey("ClearingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", "FinancialInstitution")
                        .WithMany("ClearingHousePreferences")
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClearingHouse");

                    b.Navigation("FinancialInstitution");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", "AchCycle")
                        .WithMany("NachaHeaders")
                        .HasForeignKey("AchCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", "ClearingHouse")
                        .WithMany()
                        .HasForeignKey("ClearingHouseId");

                    b.Navigation("AchCycle");

                    b.Navigation("ClearingHouse");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Entities.SchedulerTask.TaskDefinition", b =>
                {
                    b.Navigation("ExecutionLogs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchCycle", b =>
                {
                    b.Navigation("NachaHeaders");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.AchTransaction", b =>
                {
                    b.Navigation("Addendas");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouse", b =>
                {
                    b.Navigation("AchCycles");

                    b.Navigation("FinancialInstitutions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.ClearingHouseConfig", b =>
                {
                    b.Navigation("ClearingHouses");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Emails");

                    b.Navigation("Phones");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.FinancialInstitution", b =>
                {
                    b.Navigation("ClearingHousePreferences");

                    b.Navigation("DestinationTransactions");

                    b.Navigation("SourceTransactions");
                });

            modelBuilder.Entity("Cfa.ACHInterbank.Domain.Models.ACH.NachaHeader", b =>
                {
                    b.Navigation("AddendaRecords");

                    b.Navigation("BatchControls");

                    b.Navigation("Batches");

                    b.Navigation("EntryDetails");

                    b.Navigation("FileControls");
                });
#pragma warning restore 612, 618
        }
    }
}
