<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DataBase\ApplicationDbContext.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="tables_sqlServer.sql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="tables_sqlServer.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cfa.ACHInterbank.Application\Cfa.ACHInterbank.Application.csproj" />
    <ProjectReference Include="..\Cfa.ACHInterbank.Domain\Cfa.ACHInterbank.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AdoNetCore.AseClient" Version="0.19.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Quartz" Version="3.15.1" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.15.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.1" />
    <PackageReference Include="Quartz.Serialization.Json" Version="3.15.1" />
  </ItemGroup>

</Project>
