<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeFrameworkVersion>10.0.5</RuntimeFrameworkVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<NoWarn>CS1591</NoWarn>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>C:\ACHInterbank\ACHInterbank\src\Cfa.ACHInterbank.Api.xml</DocumentationFile>
    <UserSecretsId>fdac4e92-4a82-41e2-80cd-245f18336eff</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\JwksController.cs" />
    <Compile Remove="Controllers\ServersController.cs" />
    <Compile Remove="Controllers\TestsController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="NLog.config" />
  </ItemGroup>

  <ItemGroup>
    <None Include="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cfa.ACHInterbank.Application\Cfa.ACHInterbank.Application.csproj" />
    <ProjectReference Include="..\Cfa.ACHInterbank.Domain\Cfa.ACHInterbank.Domain.csproj" />
    <ProjectReference Include="..\Cfa.ACHInterbank.External\Cfa.ACHInterbank.External.csproj" />
    <ProjectReference Include="..\Cfa.ACHInterbank.Persistence\Cfa.ACHInterbank.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="NLog" Version="6.1.1" />
    <PackageReference Include="NLog.Database" Version="6.0.3" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.2" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.9" />
  </ItemGroup>

</Project>
