using Cfa.ACHInterbank.Application.DataBase;
using Cfa.ACHInterbank.Domain.Entities.Navigation;
using Cfa.ACHInterbank.Domain.Models.Configurations;
using Cfa.ACHInterbank.Persistence.Configuration;
using Cfa.ACHInterbank.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;

namespace Cfa.ACHInterbank.Persistence.Navigation.Seeders;

[Scoped]
public sealed class NachaSecurityMenuSeeder : IDbSeeder
{
    private readonly AchDbContext _context;

    public NachaSecurityMenuSeeder(AchDbContext context)
    {
        _context = context;
    }

    public int Order => 0;

    public async Task SeedAsync()
    {
        var group = await UpsertMenuItemAsync(
            MenuItemConfiguration.NachaSecurityId,
            parentId: null,
            label: "Seguridad NACHA",
            route: "/nacha-security",
            icon: "security",
            order: 8);

        var certificates = await UpsertMenuItemAsync(
            MenuItemConfiguration.NachaCertificatesId,
            group.Id,
            "Certificados digitales",
            "/nacha-security/certificates",
            "verified_user",
            order: 1);

        await UpsertMenuItemAsync(
            MenuItemConfiguration.DigitalEnvelopeId,
            group.Id,
            "Sobre digital",
            "/nacha-security/sobre-digital",
            "lock",
            order: 2);

        // New menu rows use the SQL Server identity generated by the database.
        // Persist them before creating dependent permission rows.
        await _context.SaveChangesAsync();

        await EnsureManageCertificatesPermissionAsync(certificates.Id);
        await RemoveRoleRestrictionsAsync(group.Id, certificates.Id, MenuItemConfiguration.DigitalEnvelopeId);
        await DisableDuplicateCertificateRoutesAsync(certificates.Id);

        await _context.SaveChangesAsync();
    }

    private async Task<MenuItem> UpsertMenuItemAsync(
        int id,
        int? parentId,
        string label,
        string route,
        string icon,
        int order)
    {
        var item = await _context.MenuItems.FirstOrDefaultAsync(x => x.Id == id)
            ?? await _context.MenuItems.FirstOrDefaultAsync(x =>
                x.ParentId == parentId && x.Route == route);
        if (item is null)
        {
            item = new MenuItem();
            _context.MenuItems.Add(item);
        }

        item.MenuId = MenuConfiguration.MainMenuId;
        item.ParentId = parentId;
        item.Label = label;
        item.Route = route;
        item.Icon = icon;
        item.Order = order;
        item.Exact = true;
        item.IsActive = true;

        return item;
    }

    private async Task EnsureManageCertificatesPermissionAsync(int menuItemId)
    {
        var permissions = await _context.MenuItemPermissions
            .Where(x => x.MenuItemId == menuItemId)
            .ToListAsync();

        foreach (var permission in permissions.Where(x => x.PermissionId != PermissionConfiguration.ManageCertificatesPermissionId))
        {
            _context.MenuItemPermissions.Remove(permission);
        }

        if (!permissions.Any(x => x.PermissionId == PermissionConfiguration.ManageCertificatesPermissionId))
        {
            _context.MenuItemPermissions.Add(new MenuItemPermission
            {
                MenuItemId = menuItemId,
                PermissionId = PermissionConfiguration.ManageCertificatesPermissionId
            });
        }
    }

    private async Task RemoveRoleRestrictionsAsync(params int[] menuItemIds)
    {
        var roles = await _context.MenuItemRoles
            .Where(x => menuItemIds.Contains(x.MenuItemId))
            .ToListAsync();

        _context.MenuItemRoles.RemoveRange(roles);
    }

    private async Task DisableDuplicateCertificateRoutesAsync(int canonicalId)
    {
        var duplicates = await _context.MenuItems
            .Where(x => x.Id != canonicalId && x.Route == "/nacha-security/certificates")
            .ToListAsync();

        foreach (var duplicate in duplicates)
        {
            duplicate.IsActive = false;
        }
    }
}
