CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AchResponses" (
    "Id" uuid NOT NULL,
    "TipoRespuesta" character varying(30) NOT NULL,
    "IdTransaccion" character varying(100) NOT NULL,
    "CodigoCamaraCompensacion" character varying(30) NOT NULL,
    "CodigoEntidadOrigen" character varying(30),
    "CodigoEntidadDestino" character varying(30),
    "CodigoEstadoExterno" character varying(30) NOT NULL,
    "CodigoCausalExterna" character varying(50),
    "IdEstadoInterno" integer,
    "IdEstadoServicioExterno" integer,
    "EstadoInternoNombre" character varying(100),
    "CausalNormalizada" character varying(50),
    "DescripcionCausal" character varying(300),
    "IdTransaccionServicioExterno" integer NOT NULL,
    "HashIdempotencia" character varying(128) NOT NULL,
    "EstadoProcesamiento" character varying(40) NOT NULL,
    "MotivoNoHomologacion" character varying(500),
    "PermiteNotificacion" boolean NOT NULL,
    "CorrelationId" character varying(100),
    "FechaRecepcion" timestamp with time zone NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "FechaActualizacion" timestamp with time zone,
    CONSTRAINT "PK_AchResponses" PRIMARY KEY ("Id")
);

CREATE TABLE "AchResponseStatusMappings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodigoCamaraCompensacion" character varying(30) NOT NULL,
    "TipoRespuesta" character varying(30) NOT NULL,
    "CodigoEstadoExterno" character varying(30) NOT NULL,
    "CodigoCausalExterna" character varying(50),
    "IdEstadoInterno" integer NOT NULL,
    "IdEstadoServicioExterno" integer NOT NULL,
    "EstadoInternoNombre" character varying(100) NOT NULL,
    "CausalNormalizada" character varying(50),
    "DescripcionCausalNormalizada" character varying(300),
    "RequiereCausal" boolean NOT NULL,
    "PermiteNotificacion" boolean NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaInicioVigencia" timestamp with time zone NOT NULL,
    "FechaFinVigencia" timestamp with time zone,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "FechaActualizacion" timestamp with time zone,
    CONSTRAINT "PK_AchResponseStatusMappings" PRIMARY KEY ("Id")
);

CREATE TABLE "AchResponseNotificationAttempts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AchResponseId" uuid NOT NULL,
    "NumeroIntento" integer NOT NULL,
    "EstadoNotificacion" character varying(40) NOT NULL,
    "IdCanal" integer NOT NULL,
    "NombreCanal" character varying(100) NOT NULL,
    "IdTransaccion" character varying(100) NOT NULL,
    "IdEstado" integer NOT NULL,
    "Causal" character varying(50),
    "IdTransaccionServicioExterno" integer NOT NULL,
    "DescripcionCausal" character varying(300),
    "RequestPayload" text,
    "ResponsePayload" text,
    "ExisteError" boolean,
    "CodigoError" character varying(100),
    "DescripcionError" character varying(500),
    "ErrorTecnico" character varying(1000),
    "FechaCreacion" timestamp with time zone NOT NULL,
    "FechaEnvio" timestamp with time zone,
    CONSTRAINT "PK_AchResponseNotificationAttempts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AchResponseNotificationAttempts_AchResponses_AchResponseId" FOREIGN KEY ("AchResponseId") REFERENCES "AchResponses" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AchRespAttempts_Estado" ON "AchResponseNotificationAttempts" ("EstadoNotificacion");

CREATE INDEX "IX_AchRespAttempts_FechaCreacion" ON "AchResponseNotificationAttempts" ("FechaCreacion");

CREATE UNIQUE INDEX "UX_AchRespAttempts_Response_Attempt" ON "AchResponseNotificationAttempts" ("AchResponseId", "NumeroIntento");

CREATE INDEX "IX_AchResponses_CorrelationId" ON "AchResponses" ("CorrelationId");

CREATE INDEX "IX_AchResponses_EstadoProcesamiento" ON "AchResponses" ("EstadoProcesamiento");

CREATE INDEX "IX_AchResponses_Filter" ON "AchResponses" ("TipoRespuesta", "CodigoCamaraCompensacion", "CodigoEstadoExterno");

CREATE INDEX "IX_AchResponses_IdTransaccion" ON "AchResponses" ("IdTransaccion");

CREATE UNIQUE INDEX "UX_AchResponses_HashIdempotencia" ON "AchResponses" ("HashIdempotencia");

CREATE INDEX "IX_AchRespStatusMap_Causal" ON "AchResponseStatusMappings" ("CodigoCamaraCompensacion", "TipoRespuesta", "CodigoEstadoExterno", "CodigoCausalExterna", "Activo");

CREATE INDEX "IX_AchRespStatusMap_Search" ON "AchResponseStatusMappings" ("CodigoCamaraCompensacion", "TipoRespuesta", "CodigoEstadoExterno", "Activo");

CREATE INDEX "IX_AchRespStatusMap_Vigency" ON "AchResponseStatusMappings" ("FechaInicioVigencia", "FechaFinVigencia");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260509224122_AddAchResponseStatusMappingsAndAuditTables', '10.0.5');

COMMIT;

